### ISSUE TITLE
Indoor Motion Sensor

### ISSUE THREAD

**Issue by MisterWil** [MisterWil/abodepy#13]
```json
{
    "id": "RF:001d2730",
    "type_tag": "device_type.pir",
    "type": "IR",
    "name": "Foyer Motion",
    "area": "1",
    "zone": "13",
    "sort_order": null,
    "is_window": "",
    "bypass": "0",
    "schar_24hr": "0",
    "sresp_mode_0": "0",
    "sresp_entry_0": "0",
    "sresp_exit_0": "0",
    "sresp_mode_1": "5",
    "sresp_entry_1": "4",
    "sresp_exit_1": "0",
    "sresp_mode_2": "0",
    "sresp_entry_2": "4",
    "sresp_exit_2": "0",
    "sresp_mode_3": "0",
    "sresp_entry_3": "0",
    "sresp_exit_3": "0",
    "version": "",
    "origin": "abode",
    "has_subscription": null,
    "control_url": "",
    "deep_link": null,
    "status_color": "#5cb85c",
    "faults": {
      "low_battery": 0,
      "tempered": 0,
      "supervision": 0,
      "out_of_order": 0,
      "no_response": 0
    },
    "status": "Online",
    "statuses": {
      "hvac_mode": null
    },
    "status_ex": "",
    "actions": [],
    "status_icons": [],
    "model": "L1",
    "icon": "assets/icons/motioncamera-a.svg"
  }
```

**Comment by MisterWil** [comment]
Finished in v0.10.0

**Comment by johnnyletrois** [comment]
So we can see online and offline state but not activity, correct? I set up a motion-triggered automation and this is my abodepy output:

2017-09-21 19:34:21 INFO (SocketIOThread) [abodecl] 418 Basement Motion (ID: RF:XXXXXX) - IR - Online, At: 2017-09-21 19:34:21
2017-09-21 19:34:26 INFO (SocketIOThread) [abodecl] Status Automation : Basement motion detected - Status Automation at 09/21/2017 12:34 PM

I would love to be able to use my abode PIR motion detectors for HomeAssistant automations. It doesn't seem like that is possible without first creating an abode automation and then using that automation in HomeAssistant. Thoughts?

**Comment by MisterWil** [comment]
This is probably true, yes. I've yet to see any indication that motion/occupancy sensors have any sort of output in the device json showing that they've been triggered. However...

> 2017-09-21 19:34:21 INFO (SocketIOThread) [abodecl] 418 Basement Motion (ID: RF:XXXXXX) - IR - Online, At: 2017-09-21 19:34:21

Did this update get triggered when it detected motion?

**Comment by johnnyletrois** [comment]
Yes, but only because I set up the automation. My other PIR motion sensors that don't have automations do nothing when I walk in front of them.

**Comment by MisterWil** [comment]
Ah, damn. I was hoping that they still sent some sort of event when they detected motion. I would then guess that at present there is no way to get this data over to HA other than setting up some sort of dummy automation to trigger it. What motion sensor do you have?

**Comment by johnnyletrois** [comment]
This one: https://support.goabode.com/customer/en/portal/articles/2302702-abode-indoor-motion-sensor-installation-guide

I'm guessing a dummy automation will have to be set up and then any homeassistant automation will use the abode dummy automation as a trigger. Too bad it's so hacky.
