### ISSUE TITLE
Unable to run abodecl

### ISSUE THREAD

**Issue by arsaboo** [MisterWil/abodepy#2]
Thanks for your excellent work. I installed abodeby using 
`pip3 install abodepy` on my Ubunto box, but `python abodecl.py --username USERNAME --password PASSWORD --mode` gives me the error: `python: can't open file 'abodecl.py': [Errno 2] No such file or directory`. 

Manually searching the file `find / abodecl.py` also returns `find: ‘abodecl.py’: No such file or directory`. 

Any thoughts?

**Comment by medic459** [comment]
1) make sure you're using python 3.3

2) after I did a pip, I still had to download the project locally to my machine.  abodecl.py wasn't installed (afaik) with pip.  pip just lets the code import the abodepy library.


________________________________

**Comment by arsaboo** [comment]
`python3 -V` gives 3.5.2. Here's the output
```
arsaboo@aloknuc:~/abodepy$ python3 abodecl.py --username USERNAME --password PASSWORD --mode
Traceback (most recent call last):
  File "abodecl.py", line 66, in <module>
    get_devices=True, log_level=log_level)
  File "/home/arsaboo/abodepy/abodepy.py", line 99, in __init__
    self.get_devices()
  File "/home/arsaboo/abodepy/abodepy.py", line 252, in get_devices
    panel_response = self.send_request("get", CONST.PANEL_URL)
  File "/home/arsaboo/abodepy/abodepy.py", line 212, in send_request
    return self.send_request(method, url, headers, data, True)
  File "/home/arsaboo/abodepy/abodepy.py", line 214, in send_request
    raise AbodeException((ERROR.REQUEST))
abodepy.AbodeException: (2, 'Request failed')
```

**Comment by arsaboo** [comment]
Ok....it is working now....thanks!!
