### ISSUE TITLE
Security Issue: Specify user/password via config file rather than command line

### ISSUE THREAD

**Issue by eharris** [MisterWil/abodepy#20]
It is a rather large security problem to have user/password be on the command line, since any other user on the same machine can potentially see the login credentials simply with `ps`.

The user/password should be able to be specified via a config file of some kind.  This also makes using command line functionality easier since the user and password don't have to be specified every time.

**Comment by MisterWil** [comment]
I added this ability with the cache functionality in v0.13.1. You should be able to do `abodepy --username [username] --password [password] --cache abode.pickle` and that will generate a file named 'abode.pickle' which will contain your username, password, and the new UUID requirement. After this you can do `abodepy --cache abode.pickle` and it'll utilize the cached information.
