### ISSUE TITLE
Ability to hide "Got device update for unknown device..." from logs?

### ISSUE THREAD

**Issue by shred86** [MisterWil/abodepy#27]
Is there any way to hide the following messages from my Home Assistant logs without hiding all warning messages?

> 2018-02-20 18:56:53 WARNING (SocketIOThread) [abodepy.event_controller] Got device update for unknown device: XXX

They are coming from my Nest devices that are integrated with Abode but I don't want integrated with Home Assistant.

**Comment by MisterWil** [comment]
Changed the warning statement to a debug statement - fixed in abodepy-0.12.3

**Comment by MisterWil** [comment]
Yeah... funny story: I changed the warning on initial device lookup to a debug statement instead of this one. Whoops! I fixed it now in a different branch and it'll be in the next version.

**Comment by MisterWil** [comment]
Should actually have fixed this now in v0.13.1 :-)
