### ISSUE TITLE
Philips Hue White & Color Bulb

### ISSUE THREAD

**Issue by shred86** [MisterWil/abodepy#28]
JSON for Philips Hue bulb paired to Abode gateway.

{
    "actions": [
        {
            "label": "Switch off",
            "value": "a=1&z=29&sw=off;"
        },
        {
            "label": "Switch on",
            "value": "a=1&z=29&sw=on;"
        },
        {
            "label": "Toggle",
            "value": "a=1&z=29&sw=toggle;"
        },
        {
            "label": "0%",
            "value": "a=1&z=29&sw=0;"
        },
        {
            "label": "10%",
            "value": "a=1&z=29&sw=10;"
        },
        {
            "label": "20%",
            "value": "a=1&z=29&sw=20;"
        },
        {
            "label": "30%",
            "value": "a=1&z=29&sw=30;"
        },
        {
            "label": "40%",
            "value": "a=1&z=29&sw=40;"
        },
        {
            "label": "50%",
            "value": "a=1&z=29&sw=50;"
        },
        {
            "label": "60%",
            "value": "a=1&z=29&sw=60;"
        },
        {
            "label": "70%",
            "value": "a=1&z=29&sw=70;"
        },
        {
            "label": "80%",
            "value": "a=1&z=29&sw=80;"
        },
        {
            "label": "90%",
            "value": "a=1&z=29&sw=90;"
        },
        {
            "label": "100%",
            "value": "a=1&z=29&sw=99;"
        }
    ],
    "area": "1",
    "bypass": "0",
    "control_url": "api/v1/control/light/ZB:XXXXXX",
    "deep_link": null,
    "default_group_id": "1",
    "faults": {
        "low_battery": 0,
        "no_response": 0,
        "out_of_order": 0,
        "supervision": 0,
        "tempered": 0
    },
    "generic_type": "light",
    "group_id": "33092",
    "group_name": "Lights",
    "has_subscription": null,
    "icon": "assets/icons/unknown.svg",
    "id": "ZB:XXXXXX",
    "is_window": "",
    "name": "Bedroom Lamp",
    "origin": "abode",
    "schar_24hr": "0",
    "sort_id": "5",
    "sort_order": "",
    "sresp_24hr": "0",
    "sresp_entry_0": "0",
    "sresp_entry_1": "0",
    "sresp_entry_2": "0",
    "sresp_entry_3": "0",
    "sresp_entry_4": "0",
    "sresp_exit_0": "0",
    "sresp_exit_1": "0",
    "sresp_exit_2": "0",
    "sresp_exit_3": "0",
    "sresp_exit_4": "0",
    "sresp_mode_0": "0",
    "sresp_mode_1": "0",
    "sresp_mode_2": "0",
    "sresp_mode_3": "0",
    "sresp_mode_4": "0",
    "status": "Off",
    "statusEx": "0",
    "status_color": "#5cb85c",
    "status_ex": "",
    "status_icons": [],
    "statuses": {
        "color_mode": "0",
        "color_temp": 2695,
        "hue": 228,
        "level": "50",
        "saturation": 56,
        "switch": "0"
    },
    "type": "RGB Dimmer",
    "type_tag": "device_type.hue",
    "uuid": "<deleted>",
    "version": "LCT014",
    "zone": "29"
}

Also, I noticed when using the developer view in Chrome, this is the payload that is passed when adjusting the brightness from the Abode website:

`{action: "setpercent", percentage: 40}`

This is different than how generic dimmers seem to work which is through changing the 'level' key value pair. However, changing the 'level' key value pair still works with these Philips bulbs.

It's also executing a POST method to this URL: Request URL: https://my.goabode.com/integrations/v1/devices/deviceidehere

**Comment by shred86** [comment]
I'm working on this to get RGB support with HA. I'm able to get HA to successfully read the color settings from Abode, but the issue I'm having is setting the color via HA.

Using the Chrome developer console, it looks like to set the color via the Abode webpage, it's sending:
- Request URL: https://my.goabode.com/integrations/v1/devices/<uuid here>
- Request Method: POST
- Request Payload: {"action":"setcolor","hue":286,"saturation":72}

I created a new function (copied from the set_level function):

````
def set_color(self, color):
        """Set device color."""
        hue, saturation = color

        if self._json_state['control_url']:
            # url = CONST.BASE_URL + self._json_state['control_url']
            url = CONST.BASE_URL + 'integrations/v1/devices/' + self._json_state.get('uuid')

            color_data = {
                'action': 'setcolor',
                'hue': int(hue),
                'saturation': int(saturation)
            }

            print(color_data)

            response = self._abode.send_request(
                "post", url, data=color_data)
            response_object = json.loads(response.text)

            return True

return False
````

When I try to set the color via HA, I get the following error:

````
2018-04-14 14:45:02 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall light.turn_on: entity_id=['light.bedroom_lamp'], hs_color=(30.0, 85.71428571428571)>
Traceback (most recent call last):
  File "/Users/shred/virtualenvs/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 1002, in _event_to_service_call
    await service_handler.func(service_call)
  File "/Users/shred/virtualenvs/homeassistant/lib/python3.6/site-packages/homeassistant/components/light/__init__.py", line 360, in async_handle_light_service
    await light.async_turn_on(**params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/shred/virtualenvs/homeassistant/lib/python3.6/site-packages/homeassistant/components/light/abode.py", line 51, in turn_on
    self._device.set_color(kwargs[ATTR_HS_COLOR])
  File "/Users/shred/virtualenvs/homeassistant/lib/python3.6/site-packages/abodepy/devices/light.py", line 33, in set_color
    "post", url, data=color_data)
  File "/Users/shred/virtualenvs/homeassistant/lib/python3.6/site-packages/abodepy/__init__.py", line 401, in send_request
    return self.send_request(method, url, headers, data, True)
  File "/Users/shred/virtualenvs/homeassistant/lib/python3.6/site-packages/abodepy/__init__.py", line 403, in send_request
    raise AbodeException((ERROR.REQUEST))
abodepy.exceptions.AbodeException: Request failed
````

The error is occurring with the send_request method but I'm not quite sure why... any ideas?

**Comment by shred86** [comment]
So I just tried turning on/off the light without sending the 'Authorization' token in the header and it works fine. However, if I try to change the color without the 'Authorization' token, it does not work (401 response), so it appears it's required for changing colors but for turning the light on/off (status) or setting the brightness (level). I guess what I need to figure out now is how I can get that 'access_token' that is sent during login to pass in the headers when 'send_request' is called.

**Comment by MisterWil** [comment]
https://github.com/MisterWil/abodepy/blob/master/abodepy/__init__.py#L418

Try adding this around that line:
`headers['Authorization'] = 'Bearer ' + self._token`

Seems strange, but it might work?

**Comment by shred86** [comment]
Tried that but still getting a 401 response. Something else I tried was using the token from logging in with the web browser and that seemed to work (guessing maybe because the token was still valid since I was still logged in) and with that, I was receiving a 400 response.

The token that is passed which matches the 'Authorization' in the headers is separate from the JSON login response (it's called 'claims'). I'm not sure how to access that claims response data...

**Comment by shred86** [comment]
@MisterWil - I've created two new methods in the `AbodeDevice` object but as I'm looking at this, it seems like it would make more sense to move `set_level` (existing method), `set_color_temp` (new method) and `set_color` (new method) over to the light.py file instead of the __init__.py in the devices package. Any thoughts or would you like me to move them over with my next commit?

**Comment by shred86** [comment]
Just made a pull request which adds support for changing colors. I've only tested this with my Phillips Hue bulb and light strip which are paired with my Abode hub. Once the code is reviewed and good to go, could you please push a new Abodepy version so I can submit my Home Assistant changes.

**Comment by shred86** [comment]
Added with Abodepy 0.14.0 and my [pull request](url
https://github.com/home-assistant/home-assistant/pull/17347) was merged.
