### ISSUE TITLE
Trigger a Panic or Silent Duress Alarm?

### ISSUE THREAD

**Issue by chipriley** [MisterWil/abodepy#44]
Is it possible to programmatically trigger a panic or silent duress alarm with abodepy? Maybe I'm just missing it somewhere. I saw that timeline.py can identify those events but I'm not seeing where they can be triggered. I'm trying to use a physical button as a panic button without needing a keypad or a key fob.

**Comment by MisterWil** [comment]
As far as I am aware there are no commands that you can send to the Abode API to trigger a panic or silent alarm.

**Comment by chipriley** [comment]
>As far as I am aware there are no commands that you can send to the Abode API to trigger a panic or silent alarm.

@MisterWil is there a way to send a specific code to the system? Just hoping I could send the programmed panic code to the system to trigger it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MisterWil** [comment]
Nope, unfortunately that's all over their local RF protocol too.

**Comment by chipriley** [comment]
Interesting. I wonder why they'd leave that out of the app/API. Thanks!

**Comment by MisterWil** [comment]
I'm not sure. Maybe it exists somewhere, but for the most part if you can't control it via the phone or web apps then I can't make it happen in abodepy. On one hand I can kind of understand how they don't want to open up to be able to trigger panic alarms with a public facing API, but on the other they also allow disarming/ignoring active alarms. *shrug*
