### ISSUE TITLE
Requirement is pinned: colorlog==3.0.1

### ISSUE THREAD

**Issue by MartinHjelmare** [MisterWil/abodepy#74]
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

**Comment by MisterWil** [comment]
Would you recommend just setting the pinning to >=? Does this need to be done for all requirements?

**Comment by MartinHjelmare** [comment]
If it doesn't matter, set it to minimum what you have pinned now, 3.0.1.
